//
// Created by hendrik on 30.09.17.
//

#ifndef PLAYGROUND_GLOBALSETTINGS_H
#define PLAYGROUND_GLOBALSETTINGS_H

const int WINDOW_WIDTH = 800;
const int WINDOW_HEIGHT = 608;

#endif //PLAYGROUND_GLOBALSETTINGS_H
